### ISSUE TITLE
ruby-head is not uploaded to Travis' rubies

### ISSUE THREAD

**Issue by eregon** [travis-ci/travis-rubies#20]
It seems there are two issues currently.
- rvm is broken, seems related to installing rubygems  (why would it even try installing rubygems on a Ruby >= 2.0 ?): https://travis-ci.org/travis-ci/travis-rubies/jobs/147951463

```
ruby-head-clang - #installing rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018.
Error ... (see log)
```
- Even when the build succeeds, it seems the upload fails: https://travis-ci.org/travis-ci/travis-rubies/jobs/147060206

```
INFO[0007] uploading: /home/travis/build/travis-ci/travis-rubies/ruby-head-clang.tar.bz2 (size: 13MB)  download_url=https://s3.amazonaws.com/travis-rubies/binaries/ubuntu/12.04/x86_64/ruby-head-clang.tar.bz2
ERRO[0008] failed to upload: /home/travis/build/travis-ci/travis-rubies/ruby-head-clang.tar.bz2  err=400 Bad Request
```

As a consequence ruby-head is almost a month old on Travis currently.

**Comment by eregon** [comment]
cc @rkh @BanzaiMan

**Comment by BanzaiMan** [comment]
This is fixed now.
