### ISSUE TITLE
macOS binaries missing libruby

### ISSUE THREAD

**Issue by tobiashm** [travis-ci/travis-rubies#26]
Trying to install Ruby 2.3.3 & 2.2.6 binaries on macOS 10.12.1 (using latest RVM) I get these errors:

    Found remote file https://rubies.travis-ci.org/osx/10.12/x86_64/ruby-2.3.3.tar.bz2
    …
    Libraries missing for ruby-2.3.3: /Users/travis/.rvm/rubies/ruby-2.3.3/lib/libruby.2.3.0.dylib. Refer to your system manual for installing libraries

and

    Found remote file https://rubies.travis-ci.org/osx/10.12/x86_64/ruby-2.2.6.tar.bz2
    …
    Libraries missing for ruby-2.2.6: /Users/travis/.rvm/rubies/ruby-2.2.6/lib/libruby.2.2.0.dylib. Refer to your system manual for installing libraries

**Comment by BanzaiMan** [comment]
Are you trying to use the archive where no `travis` user exists?

**Comment by BanzaiMan** [comment]
I believe this was a side effect of getting to compile Ruby on OS X at all. https://github.com/travis-ci/travis-rubies/commit/535ac213cc5ce8389958ad3454298018468dc364

I am open to suggestions, but in the mean time, I am inclined to stop advertising these archives as usable elsewhere.

**Comment by mpapis** [comment]
@BanzaiMan the initial problem should be solved, if you point me to it - I will try to find some time to look into it ... the other options would be either removing travis from rvm advertised rubies - or split the binary rubies repository to movable and not movable

**Comment by markelog** [comment]
> I am open to suggestions, but in the mean time, I am inclined to stop advertising these archives as usable elsewhere.

Please don't do that, right now you have very great collections of ruby binaries unavailable anywhere else, compiling is the worst for the user :/ especially when compiled binaries do not give user much these days.

Would be a waste to make them specific to your environment. Especially, when it seems as an easy fix by referencing dylib to your `lib` folder relative to the `bin`?

**Comment by BanzaiMan** [comment]
@mpapis Thanks for the offer. Much appreciated. I'll post an update when I remember how it was failing before!

@markelog Understood. We'll see if we can resolve this problem. Thanks for opening this issue.

**Comment by BanzaiMan** [comment]
Just so you know… I'll be traveling to Taipei for RubyConf Taiwan for the next week; this will most likely delay my responses.

(Anyone is welcome to look at build history and my commits to be the code detective, though!)

**Comment by markelog** [comment]
And thank you for all those rubies, very cool!

**Comment by markelog** [comment]
Friendly ping... any plan for this?

**Comment by BanzaiMan** [comment]
Sorry for the delay. I'll revisit this after the New Year's.

**Comment by markelog** [comment]
Thank you, have a good one

**Comment by BanzaiMan** [comment]
@mpapis The revert of https://github.com/travis-ci/travis-rubies/commit/535ac213cc5ce8389958ad3454298018468dc364 results in https://travis-ci.org/travis-ci/travis-rubies/builds/188647343. Builds on macOS/OS X fails there. RVM is failing to find `autoreconf`, which I would have assumed to have been installed as a part of `autoconf` somehow.

**Comment by BanzaiMan** [comment]
@mpapis I can install `autoconf` from source, and the compilation goes further but then it can't find `Autom4te/ChannelDefs.pm` (https://travis-ci.org/travis-ci/travis-rubies/jobs/189235428#L794), although the file should exist (https://travis-ci.org/travis-ci/travis-rubies/jobs/189235428#L575).

Haven't figured out why this is happening.

**Comment by anothermh** [comment]
The rvm maintainers have elected to remove the Travis binaries from the available remote binaries: 

https://github.com/rvm/rvm/issues/3861
https://github.com/rvm/rvm/issues/3690

This probably closes this issue -- the binaries are not built for normal rvm users.

**Comment by markelog** [comment]
Besides the rvm there is also rbenv, chruby and ruby-install or any other possible tool that can take advantage of precompiled binaries like https://github.com/asdf-vm/asdf plugins, not to mention manual installation.

Binary installation is much less buggy and so so much easier for the consumers to work with, whereas there is effectively no benefit with compilation approach.

That is why newest platform like go, rust, node or elm distribute binaries without compilation requirement. It is to bad that official versions of python, php and ruby do not do that. And that's why it is so awesome that travis devs fixed such tremendous inconvenience

**Comment by markelog** [comment]
Hey, are you still planning to fix this issue? If policy has changed, maybe it would be the right move to remove http://rubies.travis-ci.org/ page?

**Comment by BanzaiMan** [comment]
See 7c9282b.

I am sorry that we have not been able to overcome the problem.

I'm closing this now, but if anyone has a brilliant idea, please let me know.

Thank you.

**Comment by markelog** [comment]
Nevertheless, thank you for trying :)

**Comment by TomFreudenberg** [comment]
Hi @BanzaiMan Hiro and @markelog Oleg

Its a bit outdated but since I am using now travis-ci binaries for our small RVM-MINI tool, I would like to share the infos from our issue queue https://github.com/4commerce-technologies-AG/rvm-mini/issues/5

If interested checkout how to fix the dylib errors.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
I am sorry ... spending the whole day here but couldn't get it run 100% outside the /Users/travis/.rvm space.

Dropping that item
Cheers
Tom

**Comment by TomFreudenberg** [comment]
Sorry for posting back and for ... but at least I got it running.

I will push the update to rvm-mini in a few days an will link here the changes.

Cheers
Tom

**Comment by TomFreudenberg** [comment]
Ok, its pushed.

For whom is interested checkout:

1. [function __fix_TRAVIS_CI_bindings()](https://github.com/4commerce-technologies-AG/rvm-mini/blob/master/tools/ruby-install#L235-L262)
2. [set RUBYLIB_PATH for valid rubygems.rb and rbconfig.rb](https://github.com/4commerce-technologies-AG/rvm-mini/blob/master/bin/rvm-mini.env#L21)
3. [export ENV to ruby processes](https://github.com/4commerce-technologies-AG/rvm-mini/blob/master/bin/ruby#L9)

Cheers
Tom
