### ISSUE TITLE
Incorrect ruby 2.2.x (except for 2.2.2) for mac os

### ISSUE THREAD

**Issue by markelog** [travis-ci/travis-rubies#27]
All those 2.2.x versions are actually 2.2.2 

Original issue – https://github.com/travis-ci/worker/issues/234

**Comment by BanzaiMan** [comment]
I've recompiled 2.2.3 through 2.2.10 for recent OS X releases (10.10, 10.11, 10.12). These archives are dynamically linked—meaning, they are not usable unless they are used on our build images, due to limitation by RVM (which cannot use Homebrew for static linking).
