### ISSUE TITLE
Latest builds fail while uploading to S3?

### ISSUE THREAD

**Issue by eregon** [travis-ci/travis-rubies#35]
The latest builds at https://travis-ci.org/travis-ci/travis-rubies/builds seem to timeout while uploading to S3.
Could somebody investigate?
It means the latest ruby-head is from 26 May, about a month ago.
cc @BanzaiMan

**Comment by BanzaiMan** [comment]
Fixed by https://github.com/travis-ci/travis-rubies/commit/b4bb1e16ef36094dfcbc15190258119cb7ebd290

**Comment by eregon** [comment]
Thanks!
