### ISSUE TITLE
Add Ruby 2.6.0-preview1 support.

### ISSUE THREAD

**Issue by jasnow** [travis-ci/travis-rubies#44]
Add Ruby 2.6.0-preview1 support. [Release Notice](https://www.ruby-lang.org/en/news/2018/02/24/ruby-2-6-0-preview1-released)

I hope it is okay to create this issue. If not, leave a comment and close it. Thanks.

**Comment by benoittgt** [comment]
It's nearly good now: http://rubies.travis-ci.org/

**Comment by jasnow** [comment]
Thanks

**Comment by jasnow** [comment]
Verified that this is done so closing this issue.

**Comment by benoittgt** [comment]
Thanks
