### ISSUE TITLE
ruby head [x86_64-darwin17] - OpenSSL versions

### ISSUE THREAD

**Issue by MSP-Greg** [travis-ci/travis-rubies#50]
ruby 2.6.0dev (2018-10-16 trunk 65090) [x86_64-darwin17] is being built with OpenSSL 1.1.1, but it is running with 1.1.0h.  See:

https://travis-ci.org/MSP-Greg/travis-ruby/jobs/442399213#L388-L401

**Comment by BanzaiMan** [comment]
Probably due to the differences between the macOS image that builds the archive and the one which uses it. Is this actually causing a problem?

**Comment by MSP-Greg** [comment]
@BanzaiMan

Yes, that would be the cause.  As to causing a problem, I haven't tried to look for one.  I'm also a windows type, so I can't test locally.  A few thoughts:

1. Has it been tested with the test-all & test-spec openssl, net, & open-uri tests?
2. Are all the Ruby openssl constants determined at runtime?  1.1.1 has TLSv1.3, 1.1.0 does not.  1.1.1 may also have more older API's removed.
3. A few gems (EventMachine & Puma) build with the OpenSSL package.  I did the PR that added some MacOS versions to the Puma Travis matrix, but I didn't include trunk.  There are issues there with trunk in general.  EventMachine does not test any MacOS versions.
4. I'm not really a c type, so I'm not sure what issues are involved.  There is a difference between forward & backward compatibility...

For the most part, I just wanted to point it out.  Ok to close.

Thanks, Greg

**Comment by MSP-Greg** [comment]
@BanzaiMan 

Just noticed that `ruby 2.6.0dev (2018-11-05 trunk 65547) [x86_64-darwin17]` showing 1.1.0h for both.

Thanks, Greg
