### ISSUE TITLE
Support ruby 2.7.0-preview3 in bionic

### ISSUE THREAD

**Issue by grzuy** [travis-ci/travis-rubies#60]
Hi,

Not able to find `2.7.0-preview3` with `bionic`.
https://travis-ci.org/cedarcode/cose-ruby/jobs/616384171.
Is that expected or am I missing something?

Thank you!

**Comment by jasnow** [comment]
Second the motion

**Comment by jasnow** [comment]
@grzuy - FYI: With preview3 released today - you can probably close this issue.

**Comment by jasnow** [comment]
Where is ruby 2.7.0-preview3 on http://rubies.travis-ci.org web page?

**Comment by grzuy** [comment]
I tried again today (https://travis-ci.org/cedarcode/cose-ruby/builds/616384170) and ruby 2.7.0-preview3 is available on bionic.

**Comment by grzuy** [comment]
> Where is ruby 2.7.0-preview3 on http://rubies.travis-ci.org web page?

@jasnow I guess it wasn't there before, but it appears now, both under Ubuntu 16.04 and 18.04.

**Comment by jasnow** [comment]
Today we got 2.7.0-rc1 - Time marches on.

**Comment by grzuy** [comment]
Yep...

Hopefully we get support for that soon too...
