### ISSUE TITLE
New ruby versions: 2.4.7, 2.5.6, 2.6.4

### ISSUE THREAD

**Issue by jasnow** [travis-ci/travis-rubies#61]
https://www.ruby-lang.org/en/news/2019/08/28/multiple-jquery-vulnerabilities-in-rdoc

**Comment by grzuy** [comment]
:+1: 

`2.4.7` the only one not working for me.

https://travis-ci.org/cedarcode/webauthn-ruby/builds/577989856
https://travis-ci.org/kickstarter/rack-attack/builds/578521491

**Comment by jasnow** [comment]
@grzuy - Me too

**Comment by jasnow** [comment]
And 2.3.8 works too.

**Comment by jasnow** [comment]
I also sent an email to support@travis-ci.com

**Comment by mattbrictson** [comment]
2.4.7 is working now 🎉

**Comment by jasnow** [comment]
Verified

**Comment by grzuy** [comment]
Working here too.
