### ISSUE TITLE
Ruby 2.6.5 is out - Great

### ISSUE THREAD

**Issue by jasnow** [travis-ci/travis-rubies#63]
Ruby 2.6.5 is out - https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/

**Comment by grzuy** [comment]
`2.6.5`, `2.5.7` and `2.4.9` working for me now on xenial (https://travis-ci.org/cedarcode/webauthn-ruby/builds/592584062).

**Comment by jasnow** [comment]
Fixed
