### ISSUE TITLE
Add Ruby 2.6.7, 2.7.3, (3.0.1)?

### ISSUE THREAD

**Issue by jbirdjavi** [travis-ci/travis-rubies#79]
New rubies were released on 4/5/2021, and since they're security updates, it's important to get these running soon.

**Comment by san983** [comment]
> New rubies were released on 4/5/2021, and since they're security updates, it's important to get these running soon.

It looks builds have been failing for two months already https://travis-ci.com/github/travis-ci/travis-rubies/builds with this MacOS job 

``` 
10.13
 x86_64
 Xcode: xcode9.4 C
 ```
